%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    /Users/antoinewehenkel/Documents/Ecole/2015-2016/Stats/Projet/Projet1/proba1ereSession20142015.xls
%    Worksheet: Données
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/10/19 15:56:33
function importation
%% Import the data
[~, ~, raw] = xlsread('/Users/antoinewehenkel/Documents/Ecole/2015-2016/Stats/Projet/Projet1/proba1ereSession20142015.xls','Données');
raw = raw(2:end,:);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Projet1 = data(:,1);
Projet2 = data(:,2);
Qprojet2 = data(:,3);
Theorie1 = data(:,4);
Theorie2 = data(:,5);
Theorie3 = data(:,6);
Exercice1 = data(:,7);
Exercice2 = data(:,8);
Exercice3 = data(:,9);

%% Clear temporary variables
clearvars data raw;
